name = "training-site"
pages_build_output_dir = "./dist"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "training-db"
database_id = "2ffd2245-417b-44c4-8ef6-9e998e37249e"
migrations_dir = "migrations"
