// Reads content/waiver.md and content/policies.md and writes shared/legal.generated.ts
// so both the Astro pages and the Cloudflare Functions use the exact same text.
// Rules: lines starting with ">" are editor notes and are not published.
// In waiver.md, everything after the first "---" line is notes for the builder/attorney.
import { readFileSync, writeFileSync } from 'node:fs';

const read = (f) => readFileSync(new URL(`../content/${f}`, import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const dropNotes = (s) => s.split('\n').filter((l) => !l.trimStart().startsWith('>')).join('\n').replace(/\n{3,}/g, '\n\n').trim();

const waiverRaw = read('waiver.md');
const waiver = dropNotes(waiverRaw.split(/^---\s*$/m)[0]);
const policies = dropNotes(read('policies.md'));

const out = `// GENERATED by scripts/build-legal.mjs from content/*.md. Do not edit; edit the markdown instead.
export const waiverMarkdown = ${JSON.stringify(waiver)};
export const policiesMarkdown = ${JSON.stringify(policies)};
`;
writeFileSync(new URL('../shared/legal.generated.ts', import.meta.url), out);
console.log('legal: wrote shared/legal.generated.ts');
